### ISSUE TITLE
[Bug]: Role ID in daily command for Tier III supporters hasn't been updated yet

### ISSUE THREAD

**Issue by Z3RYX** [MiraBellierr/Kannabotto#13]
The role ID for Tier 3 supporters that is checked for in the daily command for the double daily amount hasn't been updated to the new roles in the Kanna server yet.

https://github.com/MiraBellierr/Kannabotto/blob/main/commands/%5B%F0%9F%8E%A9%5D%20economy/daily.js#L104

**To Reproduce**
1. Be Tier III supporter on the Patreon
2. Be in Kanna guild
3. Use Daily command

**Expected behavior**
Being payed out 2000 coins

**Actual behavior**
Kanna pays out only 1000 coins

**Comment by MiraBellierr** [comment]
This issue has been fixed in https://github.com/MiraBellierr/Kannabotto/commit/1952934dc79aa87a44b09df8efd1652452d1ab35
