### ISSUE TITLE
[BUG] Bot leaving music channel.

### ISSUE THREAD

**Issue by hemanth351718** [MiraBellierr/Kannabotto#6]
**Describe the bug**
When we execute J.play command with arguments, Bot is sending now playing message and leaving the voice channel.

**Expected behavior**
I expected Jasmine will play music, But it is leaving the channel without playing music.

**Comment by MiraBellierr** [comment]
This bug should has been fixed by now. If it's randomly appear, the problem can be assumed comes from the discord wrapper library or the ffmpeg modules
